### ISSUE TITLE
Does not work with netcoreapp3.1

### ISSUE THREAD

**Issue by DavidSnipp** [smokedlinq/Microsoft.Azure.WebJobs.Extensions.OData#1]
When trying to use your library in my netcoreapp3.1 azure function library, I get the following error at runtime:

System.TypeLoadException: 'Could not load type 'Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'

Looks like your ODataContext.cs file has a reference to an internal Microsoft File that is no longer supported:

using Microsoft.AspNetCore.Builder.Internal;

If I just try to modify your test app to be netcoreapp3.1 and your library to be netstandard2.1, I get the following error:

error CS1705: Assembly 'Microsoft.AspNetCore.OData' with identity 'Microsoft.AspNetCore.OData, Version=7.4.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.AspNetCore.Mvc.Core' with identity 'Microsoft.AspNetCore.Mvc.Core, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

Would you be able to fix your library so that it can work in netcoreapp3.1 please?

**Comment by smokedlinq** [comment]
I've updated it to the latest function app and confirm the issue. I'm not sure I'll be able to fix this as the Microsoft.AspNetCore.OData package is not available on GitHub.

**Comment by DavidSnipp** [comment]
Would it be possible to at least use your Classes to build up a LINQ Query from an HttpRequest and a DbSet ?
I want to use it in an Azure Function:

`public static IQueryable<Customer> GetCustomers(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "customers")] HttpRequest req) {
    return new ODataParser(req, new DbContext().Customers);
}`

Your classes could then be plain netstandard2.0 and have no dependencies on netcore

**Comment by smokedlinq** [comment]
I figured this out. The library needed to target netcoreapp3.1 specifically and include a reference to the framework Microsoft.AspNetCore.App. There were some other changes between 2.2 and 3.1 that had to be resolved but it appears to be working.
